version: 1
model_name: "best_8s.engine"
model_dir: "./model"
draw_boxes: false
toggle_key_1: "y"
toggle_key_2: "u"
hold_key: "Shift"
iou_threshold: 0.8
conf_threshold: 0.6
# target_index: 1
use_pid: true
Kp: 0.20
Ki: 0.01
Kd: 0.08
